/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
    BaseContract,
    BigNumber,
    BigNumberish,
    BytesLike,
    CallOverrides,
    ContractTransaction,
    Overrides,
    PopulatedTransaction,
    Signer,
    utils,
} from "ethers"
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi"
import { Listener, Provider } from "@ethersproject/providers"
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common"

export interface IUniswapV2FactoryInterface extends utils.Interface {
    contractName: "IUniswapV2Factory"
    functions: {
        "allPairs(uint256)": FunctionFragment
        "allPairsLength()": FunctionFragment
        "createPair(address,address)": FunctionFragment
        "feeTo()": FunctionFragment
        "feeToSetter()": FunctionFragment
        "getPair(address,address)": FunctionFragment
        "migrator()": FunctionFragment
        "setFeeTo(address)": FunctionFragment
        "setFeeToSetter(address)": FunctionFragment
        "setMigrator(address)": FunctionFragment
    }

    encodeFunctionData(functionFragment: "allPairs", values: [BigNumberish]): string
    encodeFunctionData(functionFragment: "allPairsLength", values?: undefined): string
    encodeFunctionData(functionFragment: "createPair", values: [string, string]): string
    encodeFunctionData(functionFragment: "feeTo", values?: undefined): string
    encodeFunctionData(functionFragment: "feeToSetter", values?: undefined): string
    encodeFunctionData(functionFragment: "getPair", values: [string, string]): string
    encodeFunctionData(functionFragment: "migrator", values?: undefined): string
    encodeFunctionData(functionFragment: "setFeeTo", values: [string]): string
    encodeFunctionData(functionFragment: "setFeeToSetter", values: [string]): string
    encodeFunctionData(functionFragment: "setMigrator", values: [string]): string

    decodeFunctionResult(functionFragment: "allPairs", data: BytesLike): Result
    decodeFunctionResult(functionFragment: "allPairsLength", data: BytesLike): Result
    decodeFunctionResult(functionFragment: "createPair", data: BytesLike): Result
    decodeFunctionResult(functionFragment: "feeTo", data: BytesLike): Result
    decodeFunctionResult(functionFragment: "feeToSetter", data: BytesLike): Result
    decodeFunctionResult(functionFragment: "getPair", data: BytesLike): Result
    decodeFunctionResult(functionFragment: "migrator", data: BytesLike): Result
    decodeFunctionResult(functionFragment: "setFeeTo", data: BytesLike): Result
    decodeFunctionResult(functionFragment: "setFeeToSetter", data: BytesLike): Result
    decodeFunctionResult(functionFragment: "setMigrator", data: BytesLike): Result

    events: {
        "PairCreated(address,address,address,uint256)": EventFragment
    }

    getEvent(nameOrSignatureOrTopic: "PairCreated"): EventFragment
}

export type PairCreatedEvent = TypedEvent<[string, string, string, BigNumber], { token0: string; token1: string; pair: string; arg3: BigNumber }>

export type PairCreatedEventFilter = TypedEventFilter<PairCreatedEvent>

export interface IUniswapV2Factory extends BaseContract {
    contractName: "IUniswapV2Factory"
    connect(signerOrProvider: Signer | Provider | string): this
    attach(addressOrName: string): this
    deployed(): Promise<this>

    interface: IUniswapV2FactoryInterface

    queryFilter<TEvent extends TypedEvent>(
        event: TypedEventFilter<TEvent>,
        fromBlockOrBlockhash?: string | number | undefined,
        toBlock?: string | number | undefined
    ): Promise<Array<TEvent>>

    listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Array<TypedListener<TEvent>>
    listeners(eventName?: string): Array<Listener>
    removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this
    removeAllListeners(eventName?: string): this
    off: OnEvent<this>
    on: OnEvent<this>
    once: OnEvent<this>
    removeListener: OnEvent<this>

    functions: {
        allPairs(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string] & { pair: string }>

        allPairsLength(overrides?: CallOverrides): Promise<[BigNumber]>

        createPair(tokenA: string, tokenB: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>

        feeTo(overrides?: CallOverrides): Promise<[string]>

        feeToSetter(overrides?: CallOverrides): Promise<[string]>

        getPair(tokenA: string, tokenB: string, overrides?: CallOverrides): Promise<[string] & { pair: string }>

        migrator(overrides?: CallOverrides): Promise<[string]>

        setFeeTo(arg0: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>

        setFeeToSetter(arg0: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>

        setMigrator(arg0: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>
    }

    allPairs(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>

    allPairsLength(overrides?: CallOverrides): Promise<BigNumber>

    createPair(tokenA: string, tokenB: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>

    feeTo(overrides?: CallOverrides): Promise<string>

    feeToSetter(overrides?: CallOverrides): Promise<string>

    getPair(tokenA: string, tokenB: string, overrides?: CallOverrides): Promise<string>

    migrator(overrides?: CallOverrides): Promise<string>

    setFeeTo(arg0: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>

    setFeeToSetter(arg0: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>

    setMigrator(arg0: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>

    callStatic: {
        allPairs(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>

        allPairsLength(overrides?: CallOverrides): Promise<BigNumber>

        createPair(tokenA: string, tokenB: string, overrides?: CallOverrides): Promise<string>

        feeTo(overrides?: CallOverrides): Promise<string>

        feeToSetter(overrides?: CallOverrides): Promise<string>

        getPair(tokenA: string, tokenB: string, overrides?: CallOverrides): Promise<string>

        migrator(overrides?: CallOverrides): Promise<string>

        setFeeTo(arg0: string, overrides?: CallOverrides): Promise<void>

        setFeeToSetter(arg0: string, overrides?: CallOverrides): Promise<void>

        setMigrator(arg0: string, overrides?: CallOverrides): Promise<void>
    }

    filters: {
        "PairCreated(address,address,address,uint256)"(
            token0?: string | null,
            token1?: string | null,
            pair?: null,
            arg3?: null
        ): PairCreatedEventFilter
        PairCreated(token0?: string | null, token1?: string | null, pair?: null, arg3?: null): PairCreatedEventFilter
    }

    estimateGas: {
        allPairs(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

        allPairsLength(overrides?: CallOverrides): Promise<BigNumber>

        createPair(tokenA: string, tokenB: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>

        feeTo(overrides?: CallOverrides): Promise<BigNumber>

        feeToSetter(overrides?: CallOverrides): Promise<BigNumber>

        getPair(tokenA: string, tokenB: string, overrides?: CallOverrides): Promise<BigNumber>

        migrator(overrides?: CallOverrides): Promise<BigNumber>

        setFeeTo(arg0: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>

        setFeeToSetter(arg0: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>

        setMigrator(arg0: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>
    }

    populateTransaction: {
        allPairs(arg0: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>

        allPairsLength(overrides?: CallOverrides): Promise<PopulatedTransaction>

        createPair(tokenA: string, tokenB: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>

        feeTo(overrides?: CallOverrides): Promise<PopulatedTransaction>

        feeToSetter(overrides?: CallOverrides): Promise<PopulatedTransaction>

        getPair(tokenA: string, tokenB: string, overrides?: CallOverrides): Promise<PopulatedTransaction>

        migrator(overrides?: CallOverrides): Promise<PopulatedTransaction>

        setFeeTo(arg0: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>

        setFeeToSetter(arg0: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>

        setMigrator(arg0: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>
    }
}
