/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers"
import { Provider } from "@ethersproject/providers"
import type { IGnosisSafe, IGnosisSafeInterface } from "../IGnosisSafe"

const _abi = [
    {
        inputs: [],
        name: "getOwners",
        outputs: [
            {
                internalType: "address[]",
                name: "",
                type: "address[]",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "getThreshold",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
]

export class IGnosisSafe__factory {
    static readonly abi = _abi
    static createInterface(): IGnosisSafeInterface {
        return new utils.Interface(_abi) as IGnosisSafeInterface
    }
    static connect(address: string, signerOrProvider: Signer | Provider): IGnosisSafe {
        return new Contract(address, _abi, signerOrProvider) as IGnosisSafe
    }
}
